[package]
name = "record_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tableturfbattle= {path="../"}
env_logger = "0.9.1"
svg = "0.10.0"